name: Template action
description: Template action description

inputs:
  githubToken:
    required: true
    default: '${{github.token}}'
    description: GitHub access token
  bumperFile:
    required: true
    default: 'repository-activity.bumper'
    description: File to be bumped
  commitMessage:
    required: true
    description: Commit message
  dryRun:
    required: true
    default: 'false'
    description: Set to 'true' to enable dry run

runs:
  using: node20
  main: 'dist/index.js'
